import { Almacen, UnidadTransporte, Pedido, IncidenteItem, RelojSimuladoData } from '../types';

export const INITIAL_ALMACENES: Almacen[] = [
  {
    id: 1,
    codigo: 'ALM-CEN-01',
    nombre: 'Almacén Central',
    tipo: 'CENTRAL',
    ubicacion: { x: 38, y: 22 },
    stockActual: 850,
    capacidadMaxima: null,
    porcentajeOcupacion: 0,
    superaAlertaOcupacion: false,
  },
  {
    id: 2,
    codigo: 'ALM-INT-01',
    nombre: 'Intermedio N-O',
    tipo: 'INTERMEDIO',
    ubicacion: { x: 17, y: 37 },
    stockActual: 540,
    capacidadMaxima: 1000,
    porcentajeOcupacion: 52.1,
    superaAlertaOcupacion: false,
  },
  {
    id: 3,
    codigo: 'ALM-INT-02',
    nombre: 'Intermedio Este',
    tipo: 'INTERMEDIO',
    ubicacion: { x: 58, y: 24 },
    stockActual: 918,
    capacidadMaxima: 1000,
    porcentajeOcupacion: 94.3,
    superaAlertaOcupacion: true,
  },
];

export const INITIAL_UNIDADES: UnidadTransporte[] = [
  {
    id: 4,
    codigo: 'Moto M4',
    tipoNombre: 'Moto',
    capacidadMaxima: 4,
    cargaActual: 2,
    capacidadDisponible: 2,
    porcentajeCarga: 50.0,
    velocidadPromedioKmH: 12.0,
    costoPorKm: 3.00,
    estadoOperativo: 'EN_RUTA',
    colorEstado: '#2563EB',
    ubicacionActual: { x: 53, y: 12 },
    nombreConductor: 'Juan Pérez',
    turno: '07:00–15:00',
    pedidoAsignado: 'PED-2854',
    activo: true,
  },
  {
    id: 1,
    codigo: 'Auto A1',
    tipoNombre: 'Auto',
    capacidadMaxima: 24,
    cargaActual: 18,
    capacidadDisponible: 6,
    porcentajeCarga: 75.0,
    velocidadPromedioKmH: 40.0,
    costoPorKm: 8.00,
    estadoOperativo: 'EN_RUTA',
    colorEstado: '#DC2626',
    ubicacionActual: { x: 28, y: 26 },
    nombreConductor: 'Carlos López',
    turno: '07:00–15:00',
    pedidoAsignado: 'PED-2850',
    activo: true,
  },
  {
    id: 2,
    codigo: 'Moto M2',
    tipoNombre: 'Moto',
    capacidadMaxima: 8,
    cargaActual: 6,
    capacidadDisponible: 2,
    porcentajeCarga: 75.0,
    velocidadPromedioKmH: 25.0,
    costoPorKm: 6.00,
    estadoOperativo: 'EN_RUTA',
    colorEstado: '#16A34A',
    ubicacionActual: { x: 32, y: 35 },
    nombreConductor: 'Miguel Gómez',
    turno: '07:00–15:00',
    pedidoAsignado: 'PED-2852',
    activo: true,
  },
  {
    id: 3,
    codigo: 'Bici B1',
    tipoNombre: 'Bicicleta',
    capacidadMaxima: 4,
    cargaActual: 2,
    capacidadDisponible: 2,
    porcentajeCarga: 50.0,
    velocidadPromedioKmH: 14.0,
    costoPorKm: 3.00,
    estadoOperativo: 'EN_RUTA',
    colorEstado: '#CA8A04',
    ubicacionActual: { x: 42, y: 32 },
    nombreConductor: 'Pedro Castro',
    turno: '23:00–07:00',
    pedidoAsignado: 'PED-2853',
    activo: true,
  },
];

export const INITIAL_PEDIDOS: Pedido[] = [
  { id: 1, codigo: 'P1', cliente: 'Cliente P1', cantidad: 3, destino: { x: 26, y: 37 }, estado: 'EN_RUTA', criticidad: 'VERDE', colorCriticidad: '#16A34A' },
  { id: 2, codigo: 'P2', cliente: 'Cliente P2', cantidad: 4, destino: { x: 36, y: 33 }, estado: 'EN_RUTA', criticidad: 'AMBAR', colorCriticidad: '#F59E0B' },
  { id: 3, codigo: 'P3', cliente: 'Cliente P3', cantidad: 2, destino: { x: 21, y: 24 }, estado: 'REGISTRADO', criticidad: 'VERDE', colorCriticidad: '#16A34A' },
  { id: 4, codigo: 'P4', cliente: 'Cliente P4', cantidad: 5, destino: { x: 57, y: 36 }, estado: 'PLANIFICADO', criticidad: 'VERDE', colorCriticidad: '#16A34A' },
  { id: 5, codigo: 'P5', cliente: 'Cliente P5', cantidad: 2, destino: { x: 43, y: 10 }, estado: 'REGISTRADO', criticidad: 'AMBAR', colorCriticidad: '#F59E0B' },
  { id: 6, codigo: 'P6', cliente: 'Cliente P6', cantidad: 4, destino: { x: 54, y: 10 }, estado: 'EN_RUTA', criticidad: 'VERDE', colorCriticidad: '#16A34A' },
  { id: 7, codigo: 'P7', cliente: 'Cliente P7', cantidad: 1, destino: { x: 36, y: 17 }, estado: 'REGISTRADO', criticidad: 'VERDE', colorCriticidad: '#16A34A' },
];

export const INITIAL_INCIDENTES: IncidenteItem[] = [
  {
    id: 'inc-1',
    numero: 1,
    tipo: 'averia',
    evento: 'Avería: Tipo 2',
    ubicacion: '(40, 15) km',
    impacto: 'PED-2854 reasignado',
    dia: 1,
    hora: '19:01:02',
    estado: 'Resuelta',
  },
  {
    id: 'inc-2',
    numero: 2,
    tipo: 'bloqueo',
    evento: 'Bloqueo: Restricción',
    ubicacion: '(30,15) → (35,15)',
    impacto: 'Bici B1 +12 min',
    dia: 1,
    hora: '20:01:02',
    estado: 'En curso',
  },
];

export const INITIAL_RELOJ: RelojSimuladoData = {
  relojFormateado: 'Día 2 - 10:03:00',
  diaSimulado: 2,
  horaSimulada: '10:03:00',
  instanteActual: '2026-04-12T10:03:00',
  factorAceleracion: 1.0,
  estadoEjecucion: 'EN_EJECUCION',
  pedidosEnCurso: 200,
  totalDias: 5,
};
